### ISSUE TITLE
gulp-git outdated

### ISSUE THREAD

**Issue by tomquas** [HaNdTriX/generator-chrome-extension-kickstart#20]
gulp-git 1.x.x causes babel-register to throw an error on 'npm start'.

$ npm start
...
> npm run dev:chrome
...
> gulp --watch --vendor=chrome

[07:59:43] Requiring external module babel-register
/.../node_modules/gulp-git/node_modules/require-dir/index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/.../node_modules/gulp-git/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/.../node_modules/gulp-git/index.js:4:18)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/.../node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dev:chrome: `gulp --watch --vendor=chrome`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mailcheck@1.7.0 dev:chrome script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tom/.npm/_logs/2017-06-16T05_59_44_980Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! start: `npm run dev:chrome`
npm ERR! Exit status 1

fix for package.json:
```
-    "gulp-git": "1.x.x",
+    "gulp-git": "2.x.x",
```

env:
$ node -v
v8.1.2

**Comment by HaNdTriX** [comment]
Good catch! 
I have updated all deps to their latest versions.

Thanks for the feedback!
